ProjectInformatics/ProjectInformatics/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using ProjectInformatics.Entities;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjectInformatics.Database;
using Microsoft.Extensions.Logging;
using ProjectInformatics.Logging;

namespace ProjectInformatics.Controllers
{
    public class ChatController : Controller
    {
        private IDbService db;
        public ChatController(IDbService context, ILogger<ChatController> logger)
        {
            db = LoggingAdvice<IDbService>.Create(context, logger);
        }
        public IActionResult Support()
        {
            var messages = db.GetMessages();
            messages.Reverse();
            return View(messages);
        }
    }
}

ProjectInformatics/ProjectInformatics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="google-signin-client_id" content="326793202628-leld5v1i8qov9lvcrfgj7lj445v1bge2.apps.googleusercontent.com">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectInformatics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectInformatics</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MyServices">Services</a>
                        </li>
                        @if (User.Identity.IsAuthenticated == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout @string.Empty</a>
                            </li>
                        }
                        @if (!User.Identity.IsAuthenticated == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Support">Support</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://localhost:44368/Account/Login/signin-google" onclick="signOut();">Sign out</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AdminPage">Admin Page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ProjectInformatics - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script>
        function signOut() {
            var auth2 = gapi.auth2.getAuthInstance();
            auth2.signOut().then(function () {
                console.log('User signed out.');
            });
        }
    </script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: true)
</body>
</html>